#!/usr/bin/perl
# SCRIPT: rebuild_webalizer_hist.pl
# PURPOSE: rebuild a corrupted/empty or missing webalizer.hist file from the usage_YYYYMM.html
# files.  
#
my $VERSION="1.0-BETA";

use strict;
use File::Copy qw(move);
&module_sanity_check;

my $ACCT=@ARGV[0];
chomp($ACCT);
if ($ACCT eq "") {
   &Usage;
}

my $HomeDir;
my $uid;
my $gid;
my $BASEDIR;
my @BASEDIR;
my $FILE;
my @sorted;
my @reversed;
my @USAGEFILES;
my $line;
my $newline;
my $DATE;
my @DATES;
my $YEAR;
my $MONTH;
my $clean_date;
my $passline;
my @PASSWDS;

open(PASSWD,"/etc/passwd");
@PASSWDS=<PASSWD>;
close(PASSWD);
foreach $passline(@PASSWDS) {
   chomp($passline);
   if ($passline =~ m/\b$ACCT\b/) {
      ($HomeDir)=(split(/:/,$passline))[5];
      ($uid)=(split(/:/,$passline))[2];
      ($gid)=(split(/:/,$passline))[3];
      last;
   }
}
if (!($HomeDir)) { 
   print "Error: $ACCT not found!\n";
   exit;
}
else { 
   $BASEDIR="$HomeDir/tmp/webalizer";
}

# check to see if the /home/cPUser/tmp/webalizer directory exists.  Bail if it doesn't.
# It means that Webalizer is not configured.

if (!(-e("$BASEDIR"))) { 
	print "Error: webalizer may not be configured for $ACCT\n";
	exit;
}

# Backup current webalizer.hist file (if it exists)
my $now = time();
my $backupfilename="webalizer.hist.$now";
print "Backing up $BASEDIR/webalizer.hist to $BASEDIR/$backupfilename - ";
move("$BASEDIR/webalizer.hist","$BASEDIR/$backupfilename");
print "Done\n";

opendir(BASEDIR,"$BASEDIR");
@BASEDIR=readdir(BASEDIR);
closedir(BASEDIR);

# first we need to sort the usage_ files by date order (newest first).  
foreach $FILE(@BASEDIR) { 
   chomp($FILE);
   if (substr($FILE,0,6) eq "usage_") { 
      $FILE =~ s/usage_//g;
      $FILE =~ s/\.html//g;
      push(@USAGEFILES,$FILE);
   }
}
@sorted=sort(@USAGEFILES);
@reversed=reverse(@sorted);
@USAGEFILES=undef;
splice(@USAGEFILES);
foreach $line(@reversed) {
   chomp($line);
   $newline = "usage_$line.html";
   push(@USAGEFILES,$newline);
}

# Now process each usage_YYYYMM.html file.
print "Processing each usage_YYYYMM.html file... - ";
my $x;
my $hs;
my $first;
my $last;
my @webstats;
my $string;

foreach $FILE(@USAGEFILES) { 
   chomp($FILE);
   $DATE=substr($FILE,6);
   $YEAR=substr($DATE,0,4);
   $MONTH=substr($DATE,4);
   $MONTH =~ s/\.html//g;
   $MONTH =~ s/^0//g;
   $x=0;
   @DATES=undef;
   open(FH,"$BASEDIR/$FILE");
   while (<FH>) {
      chomp($_);
      if ($_ =~ m/<B>(.*?)<\/B>/ and $x<6) { 
         my $hs = HTML::Strip->new();
         my $clean_text = $hs->parse( $_ );
         $hs->eof;
         push(@webstats, "$clean_text");
         $x++;   
      }   
      # Get first and last date (from range of dates 
      # between "Daily Statistics for" and "Hourly Statistics for"
      &process_dates() if /Daily Statistics for/;
   }
   close(FH);
   $first=shift(@DATES);
   $first=shift(@DATES);
   $last=pop(@DATES);
   chomp($first);
   chomp($last);
   if (@webstats[0] eq "") { 
      shift(@webstats);
   }
   $string = "$MONTH $YEAR @webstats[0] @webstats[1] @webstats[5] @webstats[4] $first $last @webstats[2] @webstats[3]";
   open(NEW,">>$BASEDIR/webalizer.hist");
   print NEW "$string\n";
   close(NEW); 
   @webstats=undef;
}

print "Done\n";
print "Fixing permissions - ";
chown $uid, $gid, "$BASEDIR/webalizer.hist";
print "Done\n";

sub process_dates {
   while ($line = <FH>, $line !~ /Hourly Statistics for/) {
      if ($line =~ m/^<TR BGCOLOR=/ or $line =~ m/^<TR><TD ALIGN=center><FONT SIZE="-1"><B>/) {
         my $hs = HTML::Strip->new();
         my $clean_date = $hs->parse( $line );
         $hs->eof;
         push(@DATES,$clean_date);
      }
   }
}       


sub Usage { 
   print "Usage: ./rebuild_webalizer_hist cPanelUser\n";
   exit;
}

sub module_sanity_check { 
   eval("use HTML::Strip;"); 
   if ($@) { 
      print "WARNING: Perl Module HTML::Strip.pm not installed!\n";
      print "Installing now - Please stand by.\n";
      system("/usr/local/cpanel/bin/cpanm --force HTML::Strip");
   }
   else { 
      print "Module HTML::Strip.pm already installed!\n";
   }
   return;
}
